group("gmp_testapps") {
  if (is_win) {
    deps = [ ":test_gmp_win", ]
  } else if (is_linux) {
    deps = [ ":test_gmp_linux", ]
  } else {
    print("GMP Test App not supported on target OS")
    print("")
  }
}

group("test_gmp_win") {
  if (is_win) {
    deps = [
      "win:test_gmp_win32_static",
      "win:test_gmp_win32_shared",
    ]
  }
}

group("test_gmp_linux") {
  if (is_linux) {
    deps = [
      "linux:test_gmp_linux_static",
      "linux:test_gmp_linux_shared",
    ]
  }
}
