#!/usr/bin/env python3
"""Generate config.m4 for the gmp-ninja asm pipeline.

This is a hand-written substitute for what GMP's `configure` would produce
in the autoconf build.  GMP's .asm files all start with::

    include(`../config.m4')

so config.m4 must be placed at the parent directory of the asm file (i.e.,
`<somewhere>/mpn/config.m4`), and m4 must be invoked with `cwd` set to the
asm file's directory (e.g., `mpn/x86_64/`).

The four supported targets (Linux x86/x64, MinGW x86/x64) differ in three
small ways:

  * GMP_LIMB_BITS / HAVE_ABI_*  -- 64 vs 32
  * include_mpn(...) chain      -- x86_64 vs x86 + dos64.m4 on MinGW
  * TYPE/SIZE/HAVE_COFF_TYPE    -- ELF .type/.size on Linux,
                                   COFF .def/.endef on MinGW

Everything else is identical across targets.
"""
import argparse
import os
import sys

# CPU/OS triple → asm config.
TEMPLATES = {
    # (cpu, os): {...}
    ("x64", "linux"): {
        "GMP_LIMB_BITS": 64,
        "ABI_DEFINE": "HAVE_ABI_64",
        "ARCH_DEFINE": "HAVE_HOST_CPU_x86_64",
        "DEFS_INCLUDE": "include_mpn(`x86_64/x86_64-defs.m4')",
        "EXTRA_INCLUDES": [],
        "TYPE":     ".type	$1,@$2",
        "SIZE":     ".size	$1,$2",
        "HAVE_COFF_TYPE": "no",
        "GSYM_PREFIX": "",
        "RODATA": "\t.section\t.rodata",
        "EXTRA_DEFINES": ["LINUX"],
    },
    ("x86", "linux"): {
        "GMP_LIMB_BITS": 32,
        "ABI_DEFINE": "HAVE_ABI_32",
        "ARCH_DEFINE": "HAVE_HOST_CPU_x86",
        "DEFS_INCLUDE": "include_mpn(`x86/x86-defs.m4')",
        "EXTRA_INCLUDES": [],
        "TYPE":     ".type	$1,@$2",
        "SIZE":     ".size	$1,$2",
        "HAVE_COFF_TYPE": "no",
        "GSYM_PREFIX": "",
        "RODATA": "\t.section\t.rodata",
        # WANT_SHLDL_CL: detected via GMP_ASM_X86_SHLDL_CL (acinclude.m4) --
        # `shldl %cl, %eax, %ebx` is accepted by all modern gas versions.
        # Set to 1 unconditionally for x86; -DWANT_SHLDL_CL=0 on the build
        # line if you ever need to support an ancient assembler.
        "EXTRA_DEFINES": ["LINUX", "WANT_SHLDL_CL"],
    },
    ("x64", "win"): {
        "GMP_LIMB_BITS": 64,
        "ABI_DEFINE": "HAVE_ABI_64",
        "ARCH_DEFINE": "HAVE_HOST_CPU_x86_64",
        "DEFS_INCLUDE": "include_mpn(`x86_64/x86_64-defs.m4')",
        "EXTRA_INCLUDES": ["include_mpn(`x86_64/dos64.m4')"],
        # MinGW's gas rejects ELF .type/.size on PE/COFF -- leave them empty
        # and rely on the COFF .def/.endef block emitted by x86_64-defs.m4
        # when HAVE_COFF_TYPE=yes.
        "TYPE": "",
        "SIZE": "",
        "HAVE_COFF_TYPE": "yes",
        "GSYM_PREFIX": "",
        "RODATA": "\t.section\t.rdata,\"dr\"",
        "EXTRA_DEFINES": [],
    },
    ("x86", "win"): {
        "GMP_LIMB_BITS": 32,
        "ABI_DEFINE": "HAVE_ABI_32",
        "ARCH_DEFINE": "HAVE_HOST_CPU_x86",
        "DEFS_INCLUDE": "include_mpn(`x86/x86-defs.m4')",
        "EXTRA_INCLUDES": [],
        "TYPE": "",
        "SIZE": "",
        "HAVE_COFF_TYPE": "yes",
        # i686 PE prepends an underscore to extern symbols.
        "GSYM_PREFIX": "_",
        "RODATA": "\t.section\t.rdata,\"dr\"",
        "EXTRA_DEFINES": ["WANT_SHLDL_CL"],
    },
}


TEMPLATE = """\
dnl config.m4.  Generated by tools/gen_config_m4.py for cpu={cpu}, os={os}.
changequote(<,>)
ifdef(<__CONFIG_M4_INCLUDED__>,,<
define(<CONFIG_TOP_SRCDIR>,<`{top_srcdir}'>)
define(<WANT_ASSERT>,0)
define(<WANT_PROFILING>,<`no'>)
define(<M4WRAP_SPURIOUS>,<no>)
define(<TEXT>, <.text>)
define(<DATA>, <.data>)
define(<LABEL_SUFFIX>, <:>)
define(<GLOBL>, <.globl>)
define(<GLOBL_ATTR>, <>)
define(<GSYM_PREFIX>, <{gsym_prefix}>)
define(<RODATA>, <{rodata}>)
define(<TYPE>, <{type_dir}>)
define(<SIZE>, <{size_dir}>)
define(<LSYM_PREFIX>, <.L>)
define(<W32>, <.long>)
define(<ALIGN_LOGARITHMIC>,<no>)
define(<ALIGN_FILL_0x90>,<yes>)
define(<HAVE_COFF_TYPE>, <{have_coff_type}>)
{extra_define_lines}
define(<SQR_TOOM2_THRESHOLD>,<34>)
define(<BMOD_1_TO_MOD_1_THRESHOLD>,<16>)
define(<SIZEOF_UNSIGNED>,<4>)
define(<GMP_LIMB_BITS>,{limb_bits})
define(<GMP_NAIL_BITS>,0)
define(<GMP_NUMB_BITS>,eval(GMP_LIMB_BITS-GMP_NAIL_BITS))
>)
changequote(`,')
ifdef(`__CONFIG_M4_INCLUDED__',,`
include(CONFIG_TOP_SRCDIR`/mpn/asm-defs.m4')
{defs_include}
{extra_includes}
define_not_for_expansion(`{arch_define}')
define_not_for_expansion(`{abi_define}')
define_not_for_expansion(`HAVE_LIMB_LITTLE_ENDIAN')
define_not_for_expansion(`HAVE_DOUBLE_IEEE_LITTLE_ENDIAN')
')
define(`__CONFIG_M4_INCLUDED__')
"""


def render(cpu: str, os_: str, top_srcdir: str) -> str:
    key = (cpu, os_)
    if key not in TEMPLATES:
        sys.exit(f"unsupported (cpu, os): {key}")
    t = TEMPLATES[key]
    extra_defines = "\n".join(
        f"define(<{name}>,1)" for name in t["EXTRA_DEFINES"]
    )
    extra_includes = "\n".join(t["EXTRA_INCLUDES"])
    return TEMPLATE.format(
        cpu=cpu,
        os=os_,
        top_srcdir=top_srcdir,
        gsym_prefix=t["GSYM_PREFIX"],
        rodata=t["RODATA"],
        type_dir=t["TYPE"],
        size_dir=t["SIZE"],
        have_coff_type=t["HAVE_COFF_TYPE"],
        extra_define_lines=extra_defines,
        limb_bits=t["GMP_LIMB_BITS"],
        defs_include=t["DEFS_INCLUDE"],
        extra_includes=extra_includes,
        arch_define=t["ARCH_DEFINE"],
        abi_define=t["ABI_DEFINE"],
    )


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cpu", required=True, choices=("x86", "x64"))
    p.add_argument("--os", required=True, choices=("linux", "win"),
                   help="`win` covers MinGW (PE/COFF); `linux` covers ELF")
    p.add_argument("--top-srcdir", required=True,
                   help="Absolute path to gmp/ srcdir (the dir holding "
                        "mpn/asm-defs.m4 etc).")
    p.add_argument("--out", required=True, help="Output config.m4 path.")
    args = p.parse_args()

    top_srcdir = os.path.abspath(args.top_srcdir)
    body = render(args.cpu, args.os, top_srcdir)

    out = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write(body)
    print(f"wrote {out} ({body.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
